zuul:
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: auth-service
      sensitive-headers: 
    miniar:
      path: /miniar/**
      serviceId: miniar
      sensitive-headers:
      